import type { CSSProperties } from "react";

export const syntaxTheme: { [key: string]: CSSProperties } = {
  'code[class*="language-"]': {
    color: "var(--color-foreground)",
    background: "none",
    textShadow: "none",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: "0.875em",
    lineHeight: "1.7",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    tabSize: 2,
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "var(--color-foreground)",
    background: "none",
    textShadow: "none",
    margin: 0,
    padding: 0,
    overflow: "auto",
  },
  comment: { color: "var(--sh-comment)", fontStyle: "italic" },
  prolog: { color: "var(--sh-comment)" },
  doctype: { color: "var(--sh-comment)" },
  cdata: { color: "var(--sh-comment)" },
  punctuation: { color: "var(--sh-punctuation)" },
  namespace: { opacity: "0.8" },
  property: { color: "var(--sh-property)" },
  tag: { color: "var(--sh-tag)" },
  boolean: { color: "var(--sh-number)" },
  number: { color: "var(--sh-number)" },
  constant: { color: "var(--sh-number)" },
  symbol: { color: "var(--sh-number)" },
  deleted: { color: "var(--sh-keyword)" },
  selector: { color: "var(--sh-string)" },
  "attr-name": { color: "var(--sh-attr)" },
  string: { color: "var(--sh-string)" },
  char: { color: "var(--sh-string)" },
  builtin: { color: "var(--sh-function)" },
  inserted: { color: "var(--sh-string)" },
  operator: { color: "var(--sh-operator)" },
  entity: { color: "var(--sh-function)", cursor: "help" },
  url: { color: "var(--sh-property)" },
  "language-css .token.string": { color: "var(--sh-string)" },
  "style .token.string": { color: "var(--sh-string)" },
  atrule: { color: "var(--sh-function)" },
  "attr-value": { color: "var(--sh-string)" },
  keyword: { color: "var(--sh-keyword)" },
  function: { color: "var(--sh-function)" },
  "class-name": { color: "var(--sh-class)" },
  regex: { color: "var(--sh-number)" },
  important: { color: "var(--sh-keyword)", fontWeight: "bold" },
  variable: { color: "var(--color-foreground)" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
};
